### ISSUE TITLE
TODO: 101

### ISSUE THREAD

**Issue by nuelmakara** [nuelmakara/google_udacity#1]
Hello Coders, the first Todo am recommending is to get rid of the woocommerce plugin as patients are not required at this stage to make payments or buy any service from the site. The hospital project is for information purposes only. Book appointments, check in and locate the various branches and get detailed information on the services the hospital offers!

**Comment by nuelmakara** [comment]
Abiodun has separated the javascript and Css files from the hospitalindex.html and also removed the woo commerce plugins therefore the issue is now resolved so am closing this particular issue!. Many thanks to you @Abiodun for a job well done!

**Comment by abbeyseto** [comment]
Hi... A little note, my handle is @abbeyseto

**Comment by nuelmakara** [comment]
ok @abbeyseto noted with thanks! @hamiduabu Thanks!
